---
- name: Create docker repository RedHat family
  shell: "{{ docker_repo }}"
  when: ansible_os_family == 'RedHat'
#
- name: Add key
  apt_key:
    url: "{{ docker_gpg_key }}"
    state: present
  when: ansible_os_family == 'Debian'
#
- name: Create docker repository Debian family
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
  when: ansible_os_family == 'Debian'
#
...
