---
- name: Install Docker RedHat family
  yum:
    name: "{{ docker_package }}"
    state: latest
  notify: restart_docker
  when: ansible_os_family == 'RedHat'
#
- name: Install Docker Debian family
  apt:
    name: "{{ docker_package }}"
    state: latest
  notify: restart_docker
  when: ansible_os_family == 'Debian'
...
