---
# tasks file for docker
#
- name: Include variables
  include_vars: "{{ ansible_os_family }}.yml"
#
- name: Import task install_required_pkg.yml
  import_tasks: install_required_pkg.yml
  tags: install_required
#
- name: Import task create_repo.yml
  import_tasks: create_repo.yml
  tags: repo
#
- name: Import task install_docker.yml
  import_tasks: install_docker.yml
  tags: install_docker
...
